apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend # Selects Pods with this label
  ports:
    - protocol: TCP
      port: 80      # Port the Service will listen on (publicly)
      targetPort: 80 # Port on the Pod (Nginx) that the Service will forward to
  type: LoadBalancer # Exposes the service externally via a cloud load balancer

