name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          
          aws-access-key-id: 
          aws-secret-access-key: 
          aws-region: us-east-1

      - name: Login to Amazon ECR
        
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push backend Docker image
        run: |
          
          docker build -t backend ./backend 
          docker tag backend 495456316485.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          docker push 495456316485.dkr.ecr.us-east-1.amazonaws.com/backend:latest

      - name: Build, tag, and push frontend Docker image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend 495456316485.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          docker push 495456316485.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Configure kubectl for EKS Access 
        run: |
          aws eks update-kubeconfig --region us-east-1 --name devops-cluster

      - name: Deploy backend to EKS
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml # Make sure this file exists

      - name: Deploy frontend to EKS
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml # Make sure this file exists

  

